function [RptgenML_CReport1] = buildreportpreprocessing
%BUILDREPORTPREPROCESSING
 
%  Auto-generated by MATLAB on 12-May-2017 16:01:13
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Format','pdf-fop',...
'Stylesheet','default-fo',...
'isIncrementFilename',true);
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('Title','Preprocessing Report');
rptgen_cfr_text1 = rptgen.cfr_text('Content',...
'This report contains information relative to the preprocessing of data.');
set(rptgen_cfr_titlepage1,'AbstractComp',rptgen_cfr_text1);
rptgen_cfr_text2 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'LegalNoticeComp',rptgen_cfr_text2);
rptgen_cfr_image1 = rptgen.cfr_image('FileName','','MaxViewportSize',[7 9]);
set(rptgen_cfr_titlepage1,'ImageComp',rptgen_cfr_image1);
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('SectionTitle','Filtering');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section2 = rptgen.cfr_section('SectionTitle','EEG filtering');
setParent(rptgen_cfr_section2,rptgen_cfr_section1);
 
% Create rptgen.crg_comment
rptgen_crg_comment1 = rptgen.crg_comment('CommentText',...
'EEG signals were filtered between');
setParent(rptgen_crg_comment1,rptgen_cfr_section2);
 
% Create rptgen.cfr_section
rptgen_cfr_section3 = rptgen.cfr_section('SectionTitle','EOG Filtering');
setParent(rptgen_cfr_section3,rptgen_cfr_section1);
 
% Create rptgen.cfr_section
rptgen_cfr_section4 = rptgen.cfr_section('SectionTitle','EMG filtering');
setParent(rptgen_cfr_section4,rptgen_cfr_section1);
 
% Create rptgen.cfr_section
rptgen_cfr_section5 = rptgen.cfr_section('SectionTitle',...
'Artefact Detection Process');
setParent(rptgen_cfr_section5,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section6 = rptgen.cfr_section('SectionTitle',...
'Noisy bad channels');
setParent(rptgen_cfr_section6,rptgen_cfr_section5);
 
